config/routes.rb
Rails.application.routes.draw do
  get 'settings/product_management'

  resources :categories do
    resources :products, only: [:show, :edit, :index]
  end
  resources :products, only: [:new, :create]

  devise_for :users
  resource :profile, only: [:edit, :update]
  resources :users, except: :show do
    member do
      patch :resend_invite
    end
  end

  [:teams, :regions, :list_roles].each do |list_items|
    resources list_items, except: :show
  end

  root "dashboard#index"
end

app/models/user.rb
class User < ApplicationRecord
  include AttributeOption
  devise :invitable, :database_authenticatable, :recoverable, :rememberable, :trackable, :validatable
  
  validates :first_name, :last_name, presence: true
  attribute_options :role, [:admin, :user]
  
  scope :active, -> { where("deleted_at IS NULL") }
  scope :sorted, -> { order(:first_name, :last_name) }
  scope :employees, -> { where(support: false) }
  
  ransacker :full_name, formatter: proc { |v| v.mb_chars.downcase.to_s } do |parent|
    Arel::Nodes::NamedFunction.new('lower', [ Arel::Nodes::NamedFunction.new('concat_ws', [ Arel::Nodes.build_quoted(' '), parent.table[:first_name], parent.table[:last_name] ])])
  end
  
  def to_s
    [first_name, last_name].select(&:present?).join(" ")
  end
  
  def soft_delete
    update_attribute(:deleted_at, Time.current)
  end
  
  def active_for_authentication?
    super && !deleted_at
  end

  def inactive_message
    !deleted_at ? super : :deleted_account
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  layout "list_items"
  responders :ajax_modal, :collection
  respond_to :js, only: [:index, :new, :create, :edit, :update]
  respond_to :html, only: [:index, :destroy, :resend_invite]

  load_and_authorize_resource

  def index
    @search = @users.ransack(params[:q])
    @search.sorts = ["first_name asc", "last_name asc"] if @search.sorts.empty?
    @users = @search.result.page(params[:page])
    respond_with(@pusers)
  end

  def new
    @user.role = User::Role::ADMIN
    respond_with(@user)
  end

  def create
    @user = User.invite!(user_params, current_user)
    respond_with(@user)
  end

  def edit
    respond_with(@user)
  end

  def update
    @user.update(user_params)
    respond_with(@user)
  end

  def destroy
    @user.soft_delete
    if @user == current_user
      sign_out(@user)
    end
    respond_with(@user)
  end
  
  def resend_invite
    if @user.invited_to_sign_up?
      @user.invite!
    end
    respond_with(@user)
  end

  protected

  def user_params
    params.require(:user).permit(:email, :first_name, :last_name, :role, :support, :phone, :time_zone)
  end
end

app/views/users/_form.html.haml
= simple_form_for(@user, remote: true) do |form|
  .modal-body
    = form.error_notification
    .row
      = form.input :first_name, wrapper_html: { class: "col-sm-6" }
      = form.input :last_name, wrapper_html: { class: "col-sm-6" }
    .row
      = form.input :email, required: true, wrapper_html: { class: "col-sm-6" }
      = form.input :phone, wrapper_html: { class: "col-sm-6" }
    .row
      = form.input :role, collection: User.roles_to_collection, wrapper_html: { class: "col-sm-6" }, input_html: { data: { "allow-clear" => false }}
      .col-sm-6
        %label Settings
        .inline-checkboxes
          = form.input :support

    = form.input :time_zone do
      = form.time_zone_select :time_zone, ActiveSupport::TimeZone.us_zones, { default: "Arizona" }, class: "form-control text-right", data: { "allow-clear" => false  }

  .modal-footer
    = form.button :submit, class: "btn btn-primary", data: { disable_with: "Please wait…" }
    = link_to "Cancel", "#", class: "btn btn-default", data: { dismiss: "modal" }, type: "button"

:javascript
  Turfandpest.Users.initForm();

app/views/users/_users.html.haml
#users
  .table-responsive
    %table.table.table-striped
      %thead
        %tr
          %th= sort_link(@search, :last_name, [:first_name, :last_name], "Name", {}, remote: true)
          %th= sort_link(@search, :email, {}, remote: true )
          %th= sort_link(@search, :phone, {}, remote: true )
          %th= sort_link(@search, :role, {}, remote: true )
          %th
          %th
      %tbody
        - @users.each do |user|
          %tr{ class: user.deleted_at ? "text-muted" : ""  }
            %td= user
            %td= user.email
            %td= user.phone
            %td= user.role_to_human
            %td.text-right
              - if user.support?
                %span.label.label-success.mr-lg Support
              - if user.deleted_at.present?
                %span.label.label-danger.mr-lg Archived
              - unless user.accepted_or_not_invited?
                %span.label.label-warning.mr-lg Pending Invitation
            %td.text-right.actions
              - unless user.deleted_at.present?
                - if user.invited_to_sign_up?
                  = link_to fa_icon("envelope-o"), resend_invite_user_path(user), title: "Resend Invite", method: :patch, data: { confirm: "Are you sure you want to resend invite?" }
                = link_to fa_icon("pencil"), edit_user_path(user), title: "Edit", data: { toggle: "ajax-modal", title: "Edit User" }
                = link_to fa_icon("ban"), user_path(user), title: "Archive", method: :delete, data: { confirm: "Are you sure you want to archive this user?" }
  .row.mt-lg
    .col-md-4
      = paginate_description @users
    .col-md-8.text-right
      = paginate @users, remote: true

app/views/users/index.html.haml
- page_title "Users"
- content_for :action_button do
  = link_to "Add User", new_user_path, class: "btn btn-primary", data: { toggle: "ajax-modal", title: "Add User" }

= search_form_for @search, remote: true do |form|
  .row
    .col-md-9
      .search-field
        = fa_icon("search")
        = form.search_field :full_name_cont, placeholder: "Search by name…", class: "form-control", autofocus: true
    .col-md-3
      = render "common/per_page"
  = render "users"

:javascript
  Turfandpest.Users.initIndex();

app/views/users/index.js.erb
<%= replace_with_render("#users", "users") %>