config/routes.rb
Rails.application.routes.draw do
  get 'settings/product_management'

  resources :categories do
    resources :products, only: [:show, :edit, :index]
  end
  resources :products, only: [:new, :create]

  devise_for :users
  resource :profile, only: [:edit, :update]
  resources :users, except: :show do
    member do
      patch :resend_invite
    end
  end

  [:teams, :regions, :list_roles].each do |list_items|
    resources list_items, except: :show
  end

  root "dashboard#index"
end

app/models/category.rb
class Category < ApplicationRecord
    has_and_belongs_to_many :products
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController

    def new
        @category = Category.new
    end
    def edit
        @category = Category.find(params[:id])
    end

    def create
        @category = Category.build(category_params)
        respond_to do |format|
            if @category.save
                format.html { redirect_to product_management_path, notice: "Nice! You just added a new category!"}
                format.json { render :product_management, status: :created, location: @category }
            else
                format.html { render :new}
                format.json { render json: @category.errors, status: :unprocessable_entity }
                flash[:alert] = "Something wen't wrong! Please try again.."
                flash[:alert] = '<span class="bolder"><i class="fa fa-exclamation-circle" aria-hidden="true"></i> Error!&nbsp; Category Not Created Because: </span><br>' + @category.errors.full_messages.join("<br>").html_safe
            end
        end
    end

    def update
        @category = Category.find(params[:id])
        respond_to do |format|
            if @category.update(category_params)
                format.html { redirect_to product_management_path, notice: "Nice! Category has been updated successfully!"}
                format.json { render :product_management, status: :updated, location: @category }
            else
                format.html { render :edit}
                format.json { render json: @category.errors, status: :unprocessable_entity }
                flash[:alert] = "Something wen't wrong! Please try again.."
                flash[:alert] = '<span class="bolder"><i class="fa fa-exclamation-circle" aria-hidden="true"></i> Error!&nbsp; Category Not Updated Because: </span><br>' + @category.errors.full_messages.join("<br>").html_safe
            end
        end
    end
    def destroy
        @category = Category.find(params[:id])
        respond_to do |format|
            if @category.destroy
                format.html { redirect_to product_management_path, notice: "Category has been deleted successfully!"}
                format.json { render :product_management, status: :destroyed, location: @category }
            else
                format.html { redirect_to product_management_path }
                format.json { render json: @category.errors, status: :unprocessable_entity }
                flash[:alert] = "Something wen't wrong! Please try again.."
                flash[:alert] = '<span class="bolder"><i class="fa fa-exclamation-circle" aria-hidden="true"></i> Error!&nbsp; Category Not Deleted Because: </span><br>' + @category.errors.full_messages.join("<br>").html_safe
            end
        end
    end

    protected

        def category_params
            params.require(:name, :subject, tags: [])
        end

end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/views/categories/_categories_master.html.haml
#category_master
	.btnBox.text-right
		= link_to new_category_path(@category), remote: true, class: "btn btn-primary btn-lg" do
			%i.fa.fa-plus
			Add new
	.table-responsive.itemsTableBox
		%table.table.table-striped.categoriesTable
			%thead
				%tr
					%th Name
					%th  # of Products
					%th
			%tbody
				- @categories.each do |category|
					%tr{id: "row_#{tier.id}"}
						%td= category.name
						%td= category.products.count
						%td.actions.text-right
							= link_to fa_icon("pencil"), edit_category_url(id: category.id), remote: true
							= link_to fa_icon("trash"), category_url(category), remote: true, title: "Delete", method: :delete, action: :destroy, data: { confirm: "Are you sure you want to delete this category?" }

	#category_modal.modal.fade

:javascript
	$('.categoriesTable').DataTable( {
		"language": {
		"search": "",
		"lengthMenu": "Display _MENU_ Categories per page",
		"zeroRecords": "No Categories Found - Click 'Add New' to create one.",
		"info": "Showing _START_ to _END_ of _TOTAL_ Total Categories",
		"infoEmpty": "No Categories Here - Click 'Add New' to create one.",
		"searchPlaceholder": "Search Categories..."
		},
		"bPaginate": false,
		"bLengthChange": false,
		"bFilter": true,
		"bInfo": false,
		"bAutoWidth": false,
		"aoColumns": [
			null,
			null,
			{ "bSortable": false }
		]
	} );