config/routes.rb
Rails.application.routes.draw do
  get 'settings/product_management'

  resources :categories do
    resources :products, only: [:show, :edit, :index]
  end
  resources :products, only: [:new, :create]

  devise_for :users
  resource :profile, only: [:edit, :update]
  resources :users, except: :show do
    member do
      patch :resend_invite
    end
  end

  [:teams, :regions, :list_roles].each do |list_items|
    resources list_items, except: :show
  end

  root "dashboard#index"
end

app/models/product.rb
class Product < ApplicationRecord
    has_and_belongs_to_many :categories
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
    def new
        # @category = Category.find(params[:category_id])
        @product = Product.new
    end
    def edit
        @category = Category.find(params[:category_id])
        @product = @category.products.find(params[:id])
    end

    def create
        @category = Category.find(params[:category_id])
        @product = @category.products.build(product_params)
        respond_to do |format|
            if @product.save
                format.html { redirect_to product_management_path, notice: "Nice! You just added a new product!"}
                format.json { render :product_management, status: :created, location: @product }
            else
                format.html { render :new}
                format.json { render json: @product.errors, status: :unprocessable_entity }
                flash[:alert] = "Something wen't wrong! Please try again.."
                flash[:alert] = '<span class="bolder"><i class="fa fa-exclamation-circle" aria-hidden="true"></i> Error!&nbsp; Product Not Created Because: </span><br>' + @product.errors.full_messages.join("<br>").html_safe
            end
        end
    end

    def update
        @category = Category.find(params[:category_id])
        @product = @category.products.find(params[:id])
        respond_to do |format|
            if @product.update(product_params)
                format.html { redirect_to product_management_path, notice: "Nice! Product has been updated successfully!"}
                format.json { render :product_management, status: :updated, location: @product }
            else
                format.html { render :edit}
                format.json { render json: @product.errors, status: :unprocessable_entity }
                flash[:alert] = "Something wen't wrong! Please try again.."
                flash[:alert] = '<span class="bolder"><i class="fa fa-exclamation-circle" aria-hidden="true"></i> Error!&nbsp; Product Not Updated Because: </span><br>' + @product.errors.full_messages.join("<br>").html_safe
            end
        end
    end
    def destroy
        @category = Category.find(params[:category_id])
        @product = @category.products.find(params[:id])
        respond_to do |format|
            if @product.destroy
                format.html { redirect_to product_management_path, notice: "Product has been deleted successfully!"}
                format.json { render :product_management, status: :destroyed, location: @product }
            else
                format.html { redirect_to product_management_path }
                format.json { render json: @product.errors, status: :unprocessable_entity }
                flash[:alert] = "Something wen't wrong! Please try again.."
                flash[:alert] = '<span class="bolder"><i class="fa fa-exclamation-circle" aria-hidden="true"></i> Error!&nbsp; Product Not Deleted Because: </span><br>' + @product.errors.full_messages.join("<br>").html_safe
            end
        end
    end

    protected

        def product_params
            params.require(:name, :category_id, :description, :size, :manufacturer, :brand, :origin, :active_ingredient, :disclaimer, :featured, :listed, :available, :amount_available, :price, :cost, :shipping_cost, :display_price, :pet_safe, :upc, :weight,  target_pests: [], size_options: [],features: [], tags: [], product_images: [])
        end
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/views/products/_form.html.haml
= form_for @product, remote: true do |f|
    .modal-body
        .inputBox
            .row
                .col-xs-12.form-group
                    = f.label :name, "Name: "
                    = f.text_field :name, class: "form-control"
            .row
                .col-xs-12.form-group
                    = f.label :description, "Description: "
                    = f.text_area :description, class: "form-control"
            .row
                .col-xs-12.col-lg-6.form-group
                    = f.label :brand, "Brand: "
                    = f.text_field :brand, class: "form-control"
                .col-xs-12.col-lg-6.form-group
                    = f.label :amount_available, "Inventory: "
                    = f.text_field :amount_available, class: "form-control"
            .row
                .col-xs-12.col-lg-6.form-group
                    = f.label :upc, "UPC: "
                    = f.text_field :upc, class: "form-control"
                .col-xs-12.col-lg-6.form-group
                    = f.label :active_ingredient, "Active Ingredient(s): "
                    = f.text_field :active_ingredient, class: "form-control"


                .row
                    .col-xs-12.form-group.categoryGroup
                        = f.hidden_field :category_id, class: "categoryField"
                        = f.label :category_id, "Select a Category"
                        .dropdown.formDropdown
                            %button.btn.dropdown-toggle.categoryDropdown{"data-toggle" => "dropdown", :type => "button"}
                                %span.categoryDropdownTitle None
                                %span.caret
                            %ul.dropdown-menu
                                %li.dropdownSearch
                                    %input.form-control{type:"text", placeholder:"Search for categories.."}
                                %li
                                    - unless @categories.blank?
                                        - @categories.each do |category|
                                            %li
                                                = link_to category.name, "#", data: {item: "#{category.name}"}, remote: true, class: "categoryItem"

    .modal-footer
        .row
            .col-xs-6.text-left
                = link_to "Cancel", "#", class: "btn btn-default cancelBtn", data: { dismiss: "modal" }, type: "button"
            .col-xs-6.text-right
                = f.button :submit, class: "btn btn-primary submitBtn btn-add-listing", data: { disable_with: "Please wait…" } do
                    Save
- if controller.action_name === "edit"
    :javascript
        $(document).ready(function() {
            // var value = $(".sportField").val();
            // $(".sportsDropdownTitle").text(value);
            // // Check boxes if values are same as name
            // $(".sameAsName").each(function() {
            //     var field = $(this).data("value");
            //     var nameValue = $(".sectionItemName").val();
            //     if($("."+field).val() === nameValue) {
            //         $(this).prop('checked', true);
            //     }
            // });
        });

:javascript

    $(document).ready(function() {
        $(".subjectField").each(function(){
            setCategorySubject($(this).val())
            $('input.tokenize').tokenfield();
        });
        $(".templateField").each(function(){
            setItemTemplate($(this).val())
        });
    });

    $('input.tokenize').on('tokenfield:removedtoken', function (e) {
        var value = e.attrs.value;
    })
    $('input.tokenize').on('tokenfield:createdtoken', function (e) {
    })

    $(".categoryItem").click(function() {
        var value = $(this).data("sport");
        $(this).closest(".categoryGroup").find(".categoryDropdownTitle").text(value);
        $(this).closest(".categoryGroup").find(".dropdown-toggle").dropdown("toggle");
        $(this).closest(".categoryGroup").find(".categoryField").val(value);
    });

    $(".catSubject").click(function() {
        var value = $(this).data("value");
        var currentValue = $(".subjectField").val();
        if ($(this).is(':checked') && currentValue.indexOf(value) !== 0) {
            newValue = currentValue.concat(value+" ");
        } else {
            newValue = currentValue.replace(value+" ", "");
        }
        $(".subjectField").val(newValue);
    });
    function setCategorySubject(value) {
        if(value === "") {
            return
        }
        $(".catSubject").each(function() {
            var checkBoxValue = $(this).data("value");
            if (~value.indexOf(checkBoxValue)){
                $(this).attr('checked', true);
            }
        });
    }
    $(document).ready(function(){
        $('[data-toggle="tooltip"]').tooltip();
    });

app/views/products/_new.html.haml
.modal-dialog
    .modal-content
        .modal-header
            %h3 Add Product
        = render partial: "form", locals: {product: @product, categories: @categories}

app/views/products/_products_master.html.haml
#category_master
	.btnBox.text-right
		= link_to new_product_path(@product), remote: true, class: "btn btn-primary btn-lg" do
			%i.fa.fa-plus
			Add new
	.table-responsive.itemsTableBox
		%table.table.table-striped.productsTable
			%thead
				%tr
					%th Thumnail
					%th Name
					%th Inventory
					%th Category
					%th Brand
					%th
			%tbody
				- @products.each do |product|
					%tr{id: "row_#{product.id}"}
						%td
							%img{src: "http://via.placeholder.com/100x100"}
						%td= product.name
						%td= product.amount_available
						%td= product.category
						%td= product.brand
						%td.actions.text-right
							= link_to fa_icon("pencil"), edit_category_product_url(id: product.id, category_id: product.category_id), remote: true
							= link_to fa_icon("trash"), category_product_url(id: product.id, category_id: product.category_id), remote: true, title: "Delete", method: :delete, action: :destroy, data: { confirm: "Are you sure you want to delete this product?" }

	#category_modal.modal.fade

:javascript
	$('.productsTable').DataTable( {
		"language": {
		"search": "",
		"lengthMenu": "Display _MENU_ Products per page",
		"zeroRecords": "No Products Found - Click 'Add New' to create one.",
		"info": "Showing _START_ to _END_ of _TOTAL_ Total Products",
		"infoEmpty": "No Products Here - Click 'Add New' to create one.",
		"searchPlaceholder": "Search Products..."
		},
		"bPaginate": false,
		"bLengthChange": false,
		"bFilter": true,
		"bInfo": false,
		"bAutoWidth": false,
		"aoColumns": [
			null,
			null,
			null,
			null,
			{ "bSortable": false }
		]
	} );

app/views/products/index.html.erb
<h1>Products#index</h1>
<p>Find me in app/views/products/index.html.erb</p>

app/views/products/new.js.erb
$('#product_modal').html("<%= j render 'new' %>");
$('#product_modal').modal('show');
// setTimeout(function(){
//     $('#product_modal .sectionItemName').focus();
// },400);

app/views/products/show.html.erb
<h1>Products#show</h1>
<p>Find me in app/views/products/show.html.erb</p>